openapi: 3.0.0
info:
  title: Pizzapp
  version: next
  description: API for the pizzapp service.
  contact:
    email: support@pizzapp.miikat.dev
  license:
    name: GNU Affero General Public License
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"
servers:
  - url: "http://localhost:5173/api"
tags:
  - name: users
    description: Get information about any user
  - name: account
    description: View and change account data
  - name: restaurants
    description: Get information about restaurants
